FROM dotnet-runtime
# This image provides a .NET Core 2.0 environment you can use to run your .NET
# applications.

ENV DOTNET_CLI_TELEMETRY_OPTOUT 1

# This setting is a workaround for issues with dotnet and certain docker versions
ENV LTTNG_UST_REGISTER_TIMEOUT 0

# Default to UTF-8 file.encoding
# Default to UTF-8 file.encoding
ENV PATH=/opt/app-root/src/.local/bin:/opt/app-root/src/bin:/opt/app-root/node_modules/.bin:${PATH} \
    STI_SCRIPTS_PATH=/usr/libexec/s2i

    
LABEL io.k8s.description="Platform for building and running .NET Core 2.0 applications"       io.k8s.display-name=".NET Core 2.0"       io.openshift.s2i.scripts-url=image:///usr/libexec/s2i       io.openshift.tags="builder,.net,dotnet,dotnetcore,rh-dotnet20"       io.openshift.expose-services="8080:http"       io.s2i.scripts-url=image:///usr/libexec/s2i

# Labels consumed by Red Hat build service
LABEL name="dotnet/dotnet-20-rhel7"       com.redhat.component="rh-dotnet20-docker"       version="2.0"       release="1"       architecture="x86_64"

# Switch to root for package installs
USER 0

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION  v8.9.1


# install Node.js
RUN  rm -R /opt/rh/rh-nodejs6 \
    && mkdir /opt/rh/rh-nodejs6 \
    && touch /opt/rh/rh-nodejs6/enable \
    && chmod a+rx /opt/rh/rh-nodejs6/enable \
    && touch ~/.bash_profile \
    && curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm ls-remote \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default \
    && npm install -g snyk \
    && chmod -R a+rwx /usr/local/nvm \
    && yum clean all -y \
    && mkdir -p /opt/app-root \
    && chmod -R a+rwx /opt/app-root \
    && chown -R 1001:0 /opt/app-root && fix-permissions /opt/app-root

# Run container by default as user with id 1001 (default)
USER 1001

env PATH "$PATH:/usr/local/nvm/versions/node/v8.9.1/bin/" 